name: flutter_base
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.5
  #GetX框架
  get: 4.6.5
  #获取包信息
  package_info_plus: 1.4.0
  #本地缓存
  shared_preferences: 2.0.15
  #屏幕比例适配
  flutter_screenutil: 5.5.3+1
  #Dialog、Popwindow、BottonSheetDialog
  flutter_smart_dialog: 4.7.0
  #下拉刷新上拉加载
  easy_refresh: 3.0.4
  #网络请求
  dio: 4.0.6
  #网络请求代理
  http_proxy: 1.2.0
  #图片加载
  extended_image: 6.2.1
  #时间格式化
  date_format: 2.0.5
  #字符串格式化
  sprintf: 6.0.0
  #虚线
  dotted_line: 3.1.0
  #精准计算
  decimal: 2.2.0
  #webView
  flutter_inappwebview: 5.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/asset/image/login/
